# Generated by Django 4.1.5 on 2023-03-14 20:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="date_created",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 3, 14, 20, 34, 29, 620670, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
